library(nycflights13)
library(tidyverse)
delay <- filter(nycflights13::flights, arr_delay >= 120)
houston <- filter(nycflights13::flights, dest %in% c('IAH', 'HOU'))
operation <- filter(nycflights13::flights, carrier %in% c('UA', 'AA', 'DL'))
summer <- filter(nycflights13::flights, month %in% c(7, 8, 9))
arrivedlate <- filter(nycflights13::flights, arr_delay > 120, dep_delay <= 0)
madeup <- filter(nycflights13::flights, dep_delay >= 60, dep_delay - arr_delay > 30)
departures <- filter(nycflights13::flights, dep_time >= 2400 | dep_time <= 600)
